export const NAVIGATION_TITLE = {
    LOGIN: 'login',
    REGISTER: 'register',
    TAB: 'tab',
    HOME: 'home',
    LOCATION: 'location',
    TRIP: 'trip',
    INFO_USER: 'info',
    HISTORY: 'history',
    DETAIL: 'detail',
    ACCOUNT: 'account',
    CALENDAR: 'calendar',
    ADD_POST: 'add-post',
    DETAIL_POST: 'detail-post',
    UPDATE_POST: 'update-post',
    ADD_SCHEDULE: 'add-schedule',
    UPDATE_SCHEDULE: 'update-schedule',
    DETAIL_SCHEDULE: 'detail-schedule',
    ADD_REVIEW: 'add-review',
    DETAIL_REVIEW: 'detail-review',
    UPDATE_REVIEW: 'update-review',
    DETAIL_PLACE: 'detail-place',

};